// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.SnippetDesigner
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSnippetDesignerPkgString = "5a3ff802-5398-465e-8cc6-882fd3cbae55";
        public static Guid guidSnippetDesignerPkg = new Guid(guidSnippetDesignerPkgString);

        public const string guidSnippetDesignerCmdSetString = "d761bf5e-28df-41a8-9168-07703f46cac1";
        public static Guid guidSnippetDesignerCmdSet = new Guid(guidSnippetDesignerCmdSetString);

        public const string guidSnippetDesignerEditorFactoryString = "9325357b-c69b-4f03-9d82-0e28723378fe";
        public static Guid guidSnippetDesignerEditorFactory = new Guid(guidSnippetDesignerEditorFactoryString);

        public const string guidImagesString = "8410c7b1-ea41-4466-b68e-fdb2e9a41237";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidHtmlEditorMenuString = "d7e8c5e1-bdb8-11d0-9c88-0000f8040a53";
        public static Guid guidHtmlEditorMenu = new Guid(guidHtmlEditorMenuString);

        public const string guidJsEditorMenuString = "d7e8c5e1-bdb8-11d0-9c88-0000f8040a53";
        public static Guid guidJsEditorMenu = new Guid(guidJsEditorMenuString);

        public const string guidAspEditorMenuString = "d7e8c5e1-bdb8-11d0-9c88-0000f8040a53";
        public static Guid guidAspEditorMenu = new Guid(guidAspEditorMenuString);

        public const string guidSqlEditorMenuString = "09e21035-245e-4ffe-ae74-105773c29cc7";
        public static Guid guidSqlEditorMenu = new Guid(guidSqlEditorMenuString);

        public const string guidCssEditorMenuString = "a764e896-518d-11d2-9a89-00c04f79efc3";
        public static Guid guidCssEditorMenu = new Guid(guidCssEditorMenuString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SnippetCtx = 0x2100;
        public const int SnippetEditGrp = 0x1030;
        public const int SnippetCustGrp = 0x1040;
        public const int SnippetExportGrp = 0x1050;
        public const int cmdidSnippetExplorer = 0x0101;
        public const int cmdidSnippetMakeReplacement = 0x0102;
        public const int cmdidExportToSnippet = 0x0103;
        public const int cmdidCreateSnippet = 0x0104;
        public const int cmdidExportToSnippetCommandLine = 0x0105;
        public const int cmdidSnippetRemoveReplacement = 0x0106;
        public const int cmdidSnippetInsertEnd = 0x0107;
        public const int cmdidSnippetInsertSelected = 0x0108;
        public const int cmdidSnippetReplacementMarker = 0x1100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int IDM_HTML_SOURCE = 0x0033;
        public const int IDM_JS_SOURCE = 0x0034;
        public const int IDM_ASP_SOURCE = 0x0035;
        public const int IDM_SQL_SOURCE = 0x5200;
        public const int IDM_CSS_SOURCE = 0x0102;
    }
}