// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.SnippetDesigner
{
    internal sealed partial class Vsix
    {
        public const string Id = "d21b0d98-7dad-421e-895e-424a0a4e6f0e";
        public const string Name = "Snippet Designer VS2022";
        public const string Description = @"Snippet Designer is a Visual Studio plug in which allows you to create and search for snippets inside the IDE";
        public const string Language = "en-US";
        public const string Version = "2.0.0";
        public const string Author = "Chris Motch";
        public const string Tags = "snippet languages editor";
    }
}
